import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { getEventWithPeople, getEventWithTimeline, getNeighborEvents } from '@/lib/queries/events';
import { getTimelineBySlug } from '@/lib/queries/timelines';
import Breadcrumbs from '@/components/Breadcrumbs';
import SEOSchema, { BreadcrumbSchema } from '@/components/SEO';
import EventHeader from '@/components/event/EventHeader';
import EventNarrative from '@/components/event/EventNarrative';
import MiniTimeline from '@/components/event/MiniTimeline';
import RelatedPeople from '@/components/event/RelatedPeople';
import EventQA from '@/components/event/EventQA';

interface EventPageProps {
  params: {
    slug: string;
    eventSlug: string;
  };
}

// Generate static params for all events (for SSG)
export async function generateStaticParams() {
  // This will be populated during build time
  // For now, return empty array - will be generated by scripts
  return [];
}

// Generate metadata for SEO
export async function generateMetadata({ params }: EventPageProps): Promise<Metadata> {
  const eventWithTimeline = await getEventWithTimeline(params.eventSlug, params.slug);
  
  if (!eventWithTimeline) {
    return {
      title: 'Event Not Found',
    };
  }

  const { timeline, ...event } = eventWithTimeline;

  return {
    title: `${event.title} (${event.start_year}) — ${timeline.title}`,
    description: event.summary || `Learn about ${event.title}, a key event in ${timeline.title} that occurred in ${event.start_year}.`,
    keywords: [
      event.title,
      timeline.title,
      `${event.start_year}`,
      ...(event.tags || []),
    ],
    openGraph: {
      title: `${event.title} — ${timeline.title}`,
      description: event.summary || '',
      type: 'article',
      url: `${process.env.NEXT_PUBLIC_SITE_URL}/timelines/${timeline.slug}/events/${event.slug}`,
    },
  };
}

// Revalidate every hour
export const revalidate = 3600;

export default async function EventPage({ params }: EventPageProps) {
  // Get the timeline first
  const timeline = await getTimelineBySlug(params.slug);
  if (!timeline) {
    notFound();
  }

  // Get the event with timeline context
  const eventWithTimeline = await getEventWithTimeline(params.eventSlug, params.slug);
  if (!eventWithTimeline) {
    notFound();
  }

  const { timeline: _, ...event } = eventWithTimeline;

  // Get event with people
  const eventWithPeople = await getEventWithPeople(params.eventSlug);
  const people = eventWithPeople?.people || [];

  // Get neighboring events
  const { before, after } = await getNeighborEvents(event.id, timeline.id, 3, 3);

  // Breadcrumb data
  const breadcrumbItems = [
    { label: 'Timelines', href: '/timelines' },
    { label: timeline.title, href: `/timelines/${timeline.slug}` },
    { label: 'Events', href: `/timelines/${timeline.slug}#events` },
  ];

  const breadcrumbSchemaItems = [
    { name: 'Home', url: `${process.env.NEXT_PUBLIC_SITE_URL}` },
    { name: 'Timelines', url: `${process.env.NEXT_PUBLIC_SITE_URL}/timelines` },
    { name: timeline.title, url: `${process.env.NEXT_PUBLIC_SITE_URL}/timelines/${timeline.slug}` },
    { name: event.title, url: `${process.env.NEXT_PUBLIC_SITE_URL}/timelines/${timeline.slug}/events/${event.slug}` },
  ];

  return (
    <>
      {/* SEO Schema */}
      <SEOSchema type="event" event={event} timeline={timeline} people={people} />
      <BreadcrumbSchema items={breadcrumbSchemaItems} />

      <div className="min-h-screen bg-parchment-50">
        {/* Breadcrumbs */}
        <div className="content-container">
          <Breadcrumbs items={breadcrumbItems} currentPage={event.title} />
        </div>

        {/* Event Header & Quick Facts */}
        <EventHeader event={event} timeline={timeline} />

        {/* Event Narrative */}
        <section className="py-12 bg-white">
          <div className="content-container">
            <EventNarrative event={event} />
          </div>
        </section>

        {/* Mini Timeline - Before/After */}
        {(before.length > 0 || after.length > 0) && (
          <section className="py-12 bg-parchment-50">
            <div className="content-container">
              <MiniTimeline
                timeline={timeline}
                currentEvent={event}
                beforeEvents={before}
                afterEvents={after}
              />
            </div>
          </section>
        )}

        {/* Related People */}
        {people.length > 0 && (
          <section className="py-12 bg-white">
            <div className="content-container">
              <RelatedPeople
                timeline={timeline}
                event={event}
                people={people}
              />
            </div>
          </section>
        )}

        {/* Event Q&A */}
        <section className="py-12 bg-parchment-50 border-t border-gray-200">
          <div className="content-container">
            <EventQA
              timeline={timeline}
              event={event}
              people={people}
            />
          </div>
        </section>
      </div>
    </>
  );
}
