import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { getTimelineFull, getTimelineHighlightEvents } from '@/lib/queries/timelines';
import { stripTimelineFormatting } from '@/lib/timelines/formatting';
import Breadcrumbs from '@/components/Breadcrumbs';
import SEOSchema, { BreadcrumbSchema } from '@/components/SEO';
import TimelineHeader from '@/components/timeline/TimelineHeader';
import CentralQuestion from '@/components/timeline/CentralQuestion';
import StoryOverview from '@/components/timeline/StoryOverview';
import KeyStoryElements from '@/components/timeline/KeyStoryElements';
import BirdsEyeStrip from '@/components/timeline/BirdsEyeStrip';
import ZoomableTimeline from '@/components/timeline/ZoomableTimeline';
import HighlightCards from '@/components/timeline/HighlightCards';
import KeyPeopleGrid from '@/components/timeline/KeyPeopleGrid';
import InterpretationSection from '@/components/timeline/InterpretationSection';
import GeminiQA from '@/components/timeline/GeminiQA';
import PerspectivesSection from '@/components/timeline/PerspectivesSection';
import DramaticSummary from '@/components/timeline/DramaticSummary';
import { parseStructuredContent } from '@/lib/timelines/structuredContent';
import { bindNarrativeData } from '@/lib/timelines/narrative';
import { getThemeColor } from '@/components/timeline/themeColors';
import type { ThemedTimelineCategory } from '@/components/timeline/types';

interface TimelinePageProps {
  params: {
    slug: string;
  };
}

// Generate static params for all timelines (for SSG)
export async function generateStaticParams() {
  // This will be populated during build time
  // For now, return empty array - will be generated by scripts
  return [];
}

// Generate metadata for SEO
export async function generateMetadata({ params }: TimelinePageProps): Promise<Metadata> {
  const timeline = await getTimelineFull(params.slug);
  
  if (!timeline) {
    return {
      title: 'Timeline Not Found',
    };
  }

  const defaultTitle = `${timeline.title} — Timeline & Key Events`;
  const metaTitle = timeline.metadata?.seo_title?.trim() || defaultTitle;

  const fallbackDescription =
    (timeline.summary && stripTimelineFormatting(timeline.summary)) ||
    `Explore the complete timeline of ${timeline.title} with key events, turning points, and historical figures from ${timeline.start_year} to ${timeline.end_year}.`;

  const metaDescription =
    timeline.metadata?.meta_description?.trim() || fallbackDescription;

  const keywordSet = new Set<string>();
  [
    timeline.title,
    'timeline',
    'history',
    timeline.region || '',
    `${timeline.start_year}`,
    `${timeline.end_year}`,
  ]
    .filter(Boolean)
    .forEach(keyword => keywordSet.add(keyword));

  (timeline.metadata?.related_keywords || [])
    .filter(Boolean)
    .forEach(keyword => keywordSet.add(keyword));

  const keywords = Array.from(keywordSet);

  return {
    title: metaTitle,
    description: metaDescription,
    keywords,
    openGraph: {
      title: metaTitle,
      description: metaDescription,
      type: 'website',
      url: `${process.env.NEXT_PUBLIC_SITE_URL}/timelines/${timeline.slug}`,
      images: timeline.map_image_url ? [timeline.map_image_url] : [],
    },
  };
}

// Revalidate every hour
export const revalidate = 3600;

export default async function TimelinePage({ params }: TimelinePageProps) {
  const timeline = await getTimelineFull(params.slug);

  if (!timeline) {
    notFound();
  }

  // Get highlight events (importance = 3)
  const highlightEvents = await getTimelineHighlightEvents(timeline.id, 8);

  const structuredContent = parseStructuredContent(
    timeline.metadata?.structured_content ?? null,
  );
  const themedCategories: ThemedTimelineCategory[] = (structuredContent?.themes || []).map(
    (theme, index) => ({
      ...theme,
      colorClass: getThemeColor(index),
    }),
  );
  const narrativeBindings = bindNarrativeData(timeline.events, structuredContent);
  const tagColorMap = timeline.events.length
    ? timeline.events.reduce<Record<string, ReturnType<typeof getThemeColor>>>((map, event) => {
        event.tags.forEach(tag => {
          if (!tag) {
            return;
          }
          if (!map[tag]) {
            const index = Object.keys(map).length;
            map[tag] = getThemeColor(index);
          }
        });
        return map;
      }, {})
    : {};

  // Breadcrumb data
  const breadcrumbItems = [
    { label: 'Timelines', href: '/timelines' },
  ];

  const breadcrumbSchemaItems = [
    { name: 'Home', url: `${process.env.NEXT_PUBLIC_SITE_URL}` },
    { name: 'Timelines', url: `${process.env.NEXT_PUBLIC_SITE_URL}/timelines` },
    { name: timeline.title, url: `${process.env.NEXT_PUBLIC_SITE_URL}/timelines/${timeline.slug}` },
  ];

  return (
    <>
      {/* SEO Schema */}
      <SEOSchema type="timeline" timeline={timeline} events={timeline.events} />
      <BreadcrumbSchema items={breadcrumbSchemaItems} />

      <div className="min-h-screen bg-parchment-50">
        {/* Breadcrumbs */}
        <div className="content-container">
          <Breadcrumbs items={breadcrumbItems} currentPage={timeline.title} />
        </div>

        {/* Header & Fast Facts */}
        <TimelineHeader timeline={timeline} />

        {/* Central Question */}
        <CentralQuestion narrative={structuredContent} />

        {/* Story Overview */}
        {structuredContent && (
          <StoryOverview narrative={structuredContent} />
        )}

        {/* Key Story Elements */}
        <KeyStoryElements
          timeline={timeline}
          narrative={structuredContent}
          categories={themedCategories}
        />

        {/* Bird's-Eye Timeline Strip */}
        <section className="py-8 bg-parchment-100">
          <div className="content-container">
            <BirdsEyeStrip
              timeline={timeline}
              events={timeline.events}
              categories={themedCategories}
              eventNarratives={narrativeBindings.eventNarratives}
              tagColorMap={tagColorMap}
            />
          </div>
        </section>

        {/* Zoomable Vertical Timeline */}
        <section className="py-12 bg-white">
          <div className="content-container">
            <ZoomableTimeline
              timeline={timeline}
              events={timeline.events}
              categories={themedCategories}
              eventNarratives={narrativeBindings.eventNarratives}
              connectors={narrativeBindings.connectors}
              tagColorMap={tagColorMap}
            />
          </div>
        </section>

        {timeline.events.length > 0 && (
          <section className="py-12 bg-parchment-100">
            <div className="content-container">
              <DramaticSummary
                timeline={timeline}
                events={timeline.events}
                tagColorMap={tagColorMap}
              />
            </div>
          </section>
        )}

        {/* Highlight Cards Section */}
        {highlightEvents.length > 0 && (
          <section className="py-12 bg-parchment-50">
            <div className="content-container">
              <HighlightCards
                timeline={timeline}
                events={highlightEvents}
                tagColorMap={tagColorMap}
              />
            </div>
          </section>
        )}

        {/* Key People Section */}
        {timeline.people.length > 0 && (
          <section className="py-12 bg-white">
            <div className="content-container">
              <KeyPeopleGrid 
                timeline={timeline}
                people={timeline.people} 
              />
            </div>
          </section>
        )}

        {/* Interpretation / Significance Section */}
        {timeline.interpretation_html && (
          <section className="py-12 bg-parchment-50">
            <div className="content-container">
              <InterpretationSection
                timeline={timeline}
                narrative={structuredContent}
                categories={themedCategories}
              />
            </div>
          </section>
        )}

        {structuredContent && (
          <section className="py-12 bg-white">
            <div className="content-container">
              <PerspectivesSection narrative={structuredContent} />
            </div>
          </section>
        )}

        {/* Gemini Q&A Panel */}
        <section className="py-12 bg-white border-t border-gray-200">
          <div className="content-container">
            <GeminiQA 
              timeline={timeline}
              events={timeline.events}
              people={timeline.people}
            />
          </div>
        </section>
      </div>
    </>
  );
}
