import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { getPersonWithEvents, getPersonWithTimeline, getPersonTimelineEvents } from '@/lib/queries/people';
import { getTimelineBySlug } from '@/lib/queries/timelines';
import Breadcrumbs from '@/components/Breadcrumbs';
import SEOSchema, { BreadcrumbSchema } from '@/components/SEO';
import PersonHeader from '@/components/person/PersonHeader';
import PersonTimeline from '@/components/person/PersonTimeline';
import PersonQA from '@/components/person/PersonQA';

interface PersonPageProps {
  params: {
    slug: string;
    personSlug: string;
  };
}

// Generate static params for all people (for SSG)
export async function generateStaticParams() {
  // This will be populated during build time
  // For now, return empty array - will be generated by scripts
  return [];
}

// Generate metadata for SEO
export async function generateMetadata({ params }: PersonPageProps): Promise<Metadata> {
  const personWithTimeline = await getPersonWithTimeline(params.personSlug, params.slug);
  
  if (!personWithTimeline) {
    return {
      title: 'Person Not Found',
    };
  }

  const { timeline, ...person } = personWithTimeline;

  const lifeDates = [
    person.birth_year ? `${person.birth_year}` : null,
    person.death_year ? `${person.death_year}` : null,
  ]
    .filter(Boolean)
    .join(' – ');

  return {
    title: `${person.name} ${lifeDates ? `(${lifeDates})` : ''} — ${timeline.title}`,
    description: person.bio_short || `Learn about ${person.name}, a key figure in ${timeline.title}.`,
    keywords: [
      person.name,
      timeline.title,
      ...(person.birth_year ? [`${person.birth_year}`] : []),
    ],
    openGraph: {
      title: `${person.name} — ${timeline.title}`,
      description: person.bio_short || '',
      type: 'profile',
      url: `${process.env.NEXT_PUBLIC_SITE_URL}/timelines/${timeline.slug}/people/${person.slug}`,
    },
  };
}

// Revalidate every hour
export const revalidate = 3600;

export default async function PersonPage({ params }: PersonPageProps) {
  // Get the timeline first
  const timeline = await getTimelineBySlug(params.slug);
  if (!timeline) {
    notFound();
  }

  // Get the person with timeline context
  const personWithTimeline = await getPersonWithTimeline(params.personSlug, params.slug);
  if (!personWithTimeline) {
    notFound();
  }

  const { timeline: _, ...person } = personWithTimeline;

  // Get person with all events
  const personWithEvents = await getPersonWithEvents(params.personSlug);
  const allEvents = personWithEvents?.events || [];

  // Get person's events within this timeline
  const timelineEvents = await getPersonTimelineEvents(person.id, timeline.id);

  // Breadcrumb data
  const breadcrumbItems = [
    { label: 'Timelines', href: '/timelines' },
    { label: timeline.title, href: `/timelines/${timeline.slug}` },
    { label: 'People', href: `/timelines/${timeline.slug}#people` },
  ];

  const breadcrumbSchemaItems = [
    { name: 'Home', url: `${process.env.NEXT_PUBLIC_SITE_URL}` },
    { name: 'Timelines', url: `${process.env.NEXT_PUBLIC_SITE_URL}/timelines` },
    { name: timeline.title, url: `${process.env.NEXT_PUBLIC_SITE_URL}/timelines/${timeline.slug}` },
    { name: person.name, url: `${process.env.NEXT_PUBLIC_SITE_URL}/timelines/${timeline.slug}/people/${person.slug}` },
  ];

  return (
    <>
      {/* SEO Schema */}
      <SEOSchema type="person" person={person} timeline={timeline} events={timelineEvents} />
      <BreadcrumbSchema items={breadcrumbSchemaItems} />

      <div className="min-h-screen bg-parchment-50">
        {/* Breadcrumbs */}
        <div className="content-container">
          <Breadcrumbs items={breadcrumbItems} currentPage={person.name} />
        </div>

        {/* Person Header & Bio */}
        <PersonHeader person={person} timeline={timeline} />

        {/* Person-Centric Timeline */}
        {timelineEvents.length > 0 && (
          <section className="py-12 bg-white">
            <div className="content-container">
              <PersonTimeline
                timeline={timeline}
                person={person}
                events={timelineEvents}
              />
            </div>
          </section>
        )}

        {/* Person Q&A */}
        <section className="py-12 bg-white border-t border-gray-200">
          <div className="content-container">
            <PersonQA
              timeline={timeline}
              person={person}
              events={timelineEvents}
            />
          </div>
        </section>
      </div>
    </>
  );
}
